#!/usr/bin/env bash
mkdir -p dist
echo "build src/ldbtn.styl -> dist/ldbtn.css ..."
./node_modules/.bin/stylus -p src/ldbtn.styl > dist/ldbtn.css
echo "minifying ldbtn.css ..."
./node_modules/.bin/uglifycss dist/ldbtn.css > dist/ldbtn.min.css
echo "done."

