#!/usr/bin/env bash
rm -rf dist
mkdir -p dist
echo "build src/index.styl -> dist/index.css ..."
./node_modules/.bin/stylus -p src/index.styl > dist/index.css
echo "minifying index.css ..."
./node_modules/.bin/uglifycss dist/index.css > dist/index.min.css
echo "done."

